AWSTemplateFormatVersion: '2010-09-09'
Description: Template to Create an EC2 instance in a VPC
Resources:
  DemoInstance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-022e1a32d3f742bd8
      InstanceType: t2.micro
      KeyName: ImportKey
      SecurityGroupIds: 
        - !Ref DemoSecurityGroup
      SubnetId: subnet-0a3ff8a6ffa4f8059
      BlockDeviceMappings:
        - DeviceName: /dev/sdm
          Ebs:
            VolumeType: io1
            Iops: 200
            DeleteOnTermination: false
            VolumeSize: 10
  DemoSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: vpc-04c7dd1feac34dbe3
      GroupDescription: SG to allow SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: '0.0.0.0/0'
      Tags:
      - Key: Name
        Value: AJ-SSH-SG